name: CI

on:
  push:
    paths:
      - "api-gateway/**"
      - "auth-service/**"
  pull_request:
    paths:
      - "api-gateway/**"
      - "auth-service/**"

jobs:
  lint-format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api-gateway, auth-service] # add all services here
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install deps
        run: npm ci
        working-directory: ${{ matrix.service }}

      - name: Lint
        run: npm run lint
        working-directory: ${{ matrix.service }}

      - name: Prettier check
        run: npm run format:check
        working-directory: ${{ matrix.service }}
